### ISSUE TITLE
Error: Metadata version mismatch for module found version 4, expected 3

### ISSUE THREAD

**Issue by gauravkukreja06** [arkon/ng-click-outside#25]
On ng-build --prod getting following error
ERROR in Error: Metadata version mismatch for module /node_modules/ng-click-outside/lib/index.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (\node_modules\@angular\compiler\bundles\compiler.umd.js:25616:34)
    at StaticSymbolResolver._createSymbolsOf (\node_modules\@angular\compiler\bundles\compiler.umd.js:25404:46)
    at StaticSymbolResolver.getSymbolsOf (\node_modules\@angular\compiler\bundles\compiler.umd.js:25385:14)
    at \node_modules\@angular\compiler\bundles\compiler.umd.js:24241:30
    at Array.forEach (native)
    at extractProgramSymbols (\node_modules\@angular\compiler\bundles\compiler.umd.js:24240:79)
    at AotCompiler.analyzeModulesAsync (\node_modules\@angular\compiler\bundles\compiler.umd.js:23796:47)
    at CodeGenerator.codegen (\node_modules\@angular\compiler-cli\src\codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (\node_modules\@angular\compiler-cli\src\ngtools_api.js:73:30)
    at _donePromise.Promise.resolve.then (\node_modules\@ngtools\webpack\src\plugin.js:391:44)

**Comment by arkon** [comment]
Try updating Angular CLI.

**Comment by deyvidfk** [comment]
@arkon  I also have the same problem and am using the latest version of angular / cli installed.

![capture](https://user-images.githubusercontent.com/5929968/33636040-9392bb22-da01-11e7-8bd9-1f69b3e7356c.PNG)

**Comment by arkon** [comment]
Ah nevermind, it actually requires Angular 5 since they made breaking changes in their AOT compiler again.

**Comment by arkon** [comment]
Published v3.1.1 which is compiled with Angular 4. Might release a major revision later on that's built for Angular 5.

**Comment by deyvidfk** [comment]
I find it very difficult to maintain compatibility with versions that theoretically should be more stable.
I hope that with each "major release" of the angular, do not generate a rework for the community in the way it is happening.

**Comment by arkon** [comment]
Yes, I'm not a fan of how Angular releases have been going, but I didn't have high expectations when they released huge breaking changes in I think Angular 2 RC4 or RC5.

That said, I don't actually use Angular anymore beyond maintaining whatever libraries I made before so I'll only continue doing so if it's reasonably easy to do so.
